# Generated by Django 4.0.8 on 2022-11-22 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                ("restaurant_name", models.CharField(max_length=200, null=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
