# Generated by Django 4.0.8 on 2022-11-24 10:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lunch_app", "0004_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
        ),
        migrations.AddField(
            model_name="vote",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
